apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-server
    spec:
      containers:
      - name: dev-server
        image: 702401326258.dkr.ecr.us-east-1.amazonaws.com/devopsproj4:latest
        ports:
        - name: http-port
          containerPort: 8080
          protocol: TCP
